const mongoose=require('mongoose')
const express=require('express')

const productSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    quantity:{
        type:{
            value:Number,
            unit:{
                type:String,
                enum:['kg','meter','sqft','piece']
            },
        },
        required:true
    },
    sold:{
        type:{
            value:Number,
            unit:{
                type:String,
                enum:['kg','meter','sqft','piece']
            },
        },
        required:true
    },

    characteristics:{
        width:{
            type:{
                value:Number,
                unit:{
                    type:String,
                    enum:['inch','ft','mm','m']
                }
            }
        },
        height:{
            type:{
                value:Number,
                unit:{
                    type:String,
                    enum:['inch','ft','mm','m']
                }
            }
        },
        thickness:{
            type:{
                value:Number,
                unit:{
                    type:String,
                    enum:['inch','ft','mm','m']
                }
            }
        },
        weight:{
            type:{
                value:Number,
                unit:{
                    type:String,
                    enum:['kg','gm']
                }
            }
        }
    },
    buyingPrice:{
        type:Number,
        required:true
    },
    maximumRetailPrice:{
        type:Number,
        required:true
    },
    specialCalculations:{
        type:{
            storingUnit:{
                type:String,
                enum:['kg','m','sqft','piece']
            },
            sellingUnit:{
                type:String,
                enum:['kg','m','sqft','piece']
            }
        },
        default:null
    },
    category:{
        name:String,
        description:String
    },
    tax:{
        type:{
            state:Number,
            central:Number
        },
        default:{
            state:9,
            central:9
        }
    }
},{timestamps:true})


const Product=new mongoose.model('Product',productSchema)

module.exports=Product;